### ISSUE TITLE
Already reported by Google Project Zero

### ISSUE THREAD

**Issue by conioh** [Mattiwatti/BSOD10#1]
You say you reported this on July 6, 2017.

Google Project Zero's James Forshaw [found and reported this on June **2016**](https://bugs.chromium.org/p/project-zero/issues/detail?id=852). So you're about a year late.

The issue also includes Microsoft response as to why they don't consider this serious enough (and why it was indeed finally fixed in RS3):

> Microsoft do not consider this issue to meet the bar for a bulletin fix because you'd need to enable the NTVDM to map the NULL page and that only works on x86. They might consider fixing it in later versions of Windows. 

A lesson might be "Google 'NtCreateProcessEx null dereference' before hurrying to post old news about it".

**Comment by Mattiwatti** [comment]
Thanks for the response and being so interested.

Please point out to me where I claimed to be "frist!!" to discover this, or that I found this in any way noteworthy at all (other than the embarrassingly poor response I received from MS). I understand that this is like a competition for you security people, but I'm really not very interested, sorry. Shouldn't I have made a post on my Medium blog announcing it otherwise? Oh wait, I don't have one. I just created a Github repo with a few lines of code that are enough to crash a modern OS, which I personally find very funny.

I would have been very surprised if I were the first to discover this, given how long the bug has existed and how easy it is to find. Neither am I surprised that the big Google security guy got an actual response from Microsoft. Not that it was a satisfying one - as I point out in the README, if it's not a remote execution exploit, Microsoft does not give a shit. Even if you work at Google.

**Comment by conioh** [comment]
I don't work at Google, Microsoft, or any company related to this issue so it's not a competition for me.

The thing is that you _presented_ this as if "Microsoft was not interested and instead unironically redirected me to the Microsoft Support Services site 'if I had any issues with Windows'." As if that's _all_ they did.

But they did give a more detailed answer - even if it's one that you don't like (and for the matter I don't like it either; it's an easy fix - one that they should have made and backported) - one that was public for quite some time.

Maybe you think Microsoft should start a lengthy discussion _every time_ someone else reports a known bug for the one hundredth time. If they did that they wouldn't have time to fix any bugs at all.

They made their decision, even if it's a stupid one. Expecting them to patiently negotiate it from the start every time someone rediscovers the bug and bugs them about it is not very reasonable.

Edit: And describing criticism of your whining as "inane" while you continue to whine and provide lame justifications for it is... as I've said, lame. Criticism is hard to deal with, but when you post thing publicly that appear 3rd in a relevant Google search, you're bound to get some. Grow up and deal with it.

**Comment by Mattiwatti** [comment]
That's a nice thought, in fact even one that I agree with. If I had received "piss off and use Google next time" as a response, that would have been perfectly fair and it would have been unreasonable to expect MS to spend more on it than that. Except I never got to report the actual bug at all, I was simply given a one-liner response redirecting me to the generic Microsoft support page. In other words, Microsoft did not know the bug was a dupe, because they didn't know what the bug was.

**Comment by conioh** [comment]
Who did you report to? Microsoft is a big company, and things are bound to get messed up if you don't contact an authority close enough to the one you really need. Did you try MSRC or Microsoft Support? 'Cause that's very likely to give you different results.

Regardless, even if Microsoft made all the possible mistakes and a few impossible ones, you still could have googled for the bug. Then at the very least you wouldn't have had any expectations about them fixing it...

**Comment by Mattiwatti** [comment]
We've already established that I agree on the second part. I should have Googled (or is it "Bing'd"?) the bug. Mea culpa. I guess it simply didn't occur to me that it would be possible that you can report a **null pointer dereference** (which takes all of 5 seconds to fix) and still not have the bug fixed until a year and a half later.

I contacted MSRC, but I don't really see how that's relevant. Of course contacting Microsoft support would have been a waste of time, but even they should ultimately have been able to forward the issue to the appropriate channel. Ironically I got _told to contact to Microsoft support_, which is about as offensive as it gets.
